# Generated by Django 3.2.7 on 2022-11-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20221113_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='dateofb',
        ),
    ]
