# Generated by Django 3.2.7 on 2022-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_dateofb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='doc', max_length=30),
        ),
        migrations.AddField(
            model_name='labassist',
            name='role',
            field=models.CharField(default='lab', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=30),
        ),
    ]
