# Generated by Django 3.2.7 on 2022-11-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20221113_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='users',
        ),
    ]
