# Generated by Django 3.2.7 on 2022-11-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='username',
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
