# Generated by Django 4.1.3 on 2022-12-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20221113_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('bdate', models.DateField()),
                ('btime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
