# Generated by Django 4.1.4 on 2022-12-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_dbook_description_dbook_age_dbook_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbook',
            name='btime',
            field=models.CharField(max_length=30),
        ),
    ]
