# Generated by Django 4.1.4 on 2022-12-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_dbook_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbook',
            name='status',
            field=models.CharField(default='true', max_length=30),
        ),
    ]
