# Generated by Django 4.1.4 on 2022-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_dbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbook',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
