# Generated by Django 4.1.4 on 2022-12-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_dbook_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dateofb',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
