# Generated by Django 4.1.4 on 2022-12-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_patient_dateofb_remove_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_num',
        ),
    ]
