# Generated by Django 4.1.4 on 2022-12-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_remove_patient_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_num',
            field=models.IntegerField(default=0),
        ),
    ]
