# Generated by Django 4.1.4 on 2022-12-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='testResult',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('uid', models.IntegerField()),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('bloodp', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fasting', models.CharField(max_length=30)),
                ('ecg', models.CharField(max_length=100)),
                ('heart', models.IntegerField()),
                ('cpain', models.CharField(max_length=30)),
                ('cpaintype', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
