# Generated by Django 4.1.4 on 2022-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_testresult_bloodp_alter_testresult_chol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBookFinish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('uid', models.IntegerField()),
                ('dname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('bdate', models.DateField()),
                ('btime', models.CharField(max_length=30)),
                ('refer', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
