# Generated by Django 4.1.4 on 2022-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_dbookfinish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbookfinish',
            name='bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbookfinish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
