# Generated by Django 4.1.4 on 2022-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_dbookfinish_bid_alter_dbookfinish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
